### ISSUE TITLE
Chest Shape

### ISSUE THREAD

**Issue by ayounglexus** [Mx772/dragons-dogma-2-auto-character-creator#11]
Found a bug with the Chest Shape slider for female humans. It seems to only input half the value. (i.e. if I set 40 in the config it will result in 20 in the creator.) I believe this is due to the Chest Shape slider uniquely using .5 increments instead of a whole value increments. Current workaround is to double the desire value in the template (If I'm aiming for 40, set the template value to 80.)

(Cool project btw)

**Comment by Mx772** [comment]
Good find!

Let me see if I can't do some logic to fix that.
