### ISSUE TITLE
Nose Bridge Issue

### ISSUE THREAD

**Issue by ayounglexus** [Mx772/dragons-dogma-2-auto-character-creator#12]
Hi, 

Found another small problem. I'm not sure if it is for all Parent/Child Sliders, but at least for Bridge Bump (Overall) in the nose section I ran into this issue.

The Template calls for the following:

bridge_bump_overall = -100
bridge_bump_upper = -90
bridge_bump_lower = -100

The Overall section works fine, setting the value to -100. When this happens, both the Upper and Lower values are set in game to -100 as well. However,  when your utility goes to edit the Upper and Lower, the in game value ends up being wildly different. This is outputted in the log as the following:

Going from 0 to -100 for bridge_bump_overall
Going from -182 to -90 for bridge_bump_upper
Going from -166 to -100 for bridge_bump_lower

In game the utility ends up setting the following values:
Overall: -100
Upper: -8
Lower: -34

I'm guessing what is happening is the utility doesn't take into account that the Upper and Lower values are capped in game at -100. This makes the utility way overshot the needed adjustment to these values. 

Thanks for all your work! I'm having a blast making templates.

**Comment by Mx772** [comment]
Another good find and you're right; doesn't take into account limits. 

That... is going to be fun.... as each category has a different min/max

Here is the ones I found:
```
attribute_dependencies = {
    "arm_size": ["upper_arm_thickness", "forearm_thickness"],
    "leg_size": ["thigh_size", "calf_size"],
    "brow_depth_overall": ["brow_depth_inner", "brow_depth_outer"],
    "bridge_bump_overall": ["bridge_bump_upper", "bridge_bump_lower"],
    "cheek_thickness": ["cheek_bulge", "neck_fat"],
    "body_tattoo_overall_scale": ["body_tattoo_vert_scale", "body_tattoo_horz_scale"],
    "right_arm_overall_scale": ["right_arm_vert_scale", "right_arm_horz_scale"],
    "left_arm_overall_scale": ["left_arm_vert_scale", "left_arm_horz_scale"],
    "right_leg_overall_scale": ["right_leg_vert_scale", "right_leg_horz_scale"],
    "left_leg_overall_scale": ["left_leg_vert_scale", "left_leg_horz_scale"],
    "body_scar_overall_scale": ["body_scar_vert_scale", "body_scar_horz_scale"],
    "right_arm_scar_overall_scale": ["right_arm_scar_horz_scale", "right_arm_scar_vert_scale"],
    "left_arm_scar_overall_scale": ["left_arm_scar_horz_scale", "left_arm_scar_vert_scale"],
    "right_leg_scar_overall_scale": ["right_leg_scar_horz_scale", "right_leg_scar_vert_scale"],
    "left_leg_scar_overall_scale": ["left_leg_scar_horz_scale", "left_leg_scar_vert_scale"],
}
```

The non-tattoo ones go from `-100` to `100`
The scar/tattoos go from `0 to 400`

But I think I have some janky logic here.

**Comment by Mx772** [comment]
```
Going from 0 to -100 for bridge_bump_overall
Going from -100 to -90 for bridge_bump_upper
Going from -100 to -100 for bridge_bump_lower
```
```
Going from 25 to 45 for left_arm_overall_scale
Going from 45 to 15 for left_arm_vert_scale
Going from 45 to 52 for left_arm_horz_scale
```


Fixed in next release.
