### ISSUE TITLE
[Preset] Ciri v3 by Jayah_

### ISSUE THREAD

**Issue by bustedkiwi** [Mx772/dragons-dogma-2-auto-character-creator#18]
[info]
name = "Ciri v3"
author = "https://www.reddit.com/user/Jayah_"
source = "https://www.reddit.com/r/fashiondogma/comments/1bhxsrd/ciri_the_witcher_3_sliders/"
photo = "https://v.redd.it/86h3f2mbx4pc1"

## Preset: 

https://pastebin.com/6NLi6rQu

**Comment by Mx772** [comment]
Thanks for uploading these :)

I assume you saw, but I also added the rest of the attributes if needed:
https://github.com/Mx772/dragons-dogma-2-auto-character-creator/blob/main/defaults/human_female.ini

(So eye 1/2, etc)

But you can leave out any that you don't change as it'll just skip that section.

**Comment by Mx772** [comment]
Just kidding, I see that you did so in the above preset, ignore me :fingerguns:

**Comment by bustedkiwi** [comment]
Haha, good to know! I have been going through testing these and I do have a weirdness with this Ciri (and the variant) when the creator gets to body tattoo 2 something goes wrong between Tattoo #1 sheen and Body tatt 2 style, it's like it got stuck going through the tattoo 2 styles instead of selecting style 36 and moving to the next option

**Comment by Mx772** [comment]
Hm, taking a look now

**Comment by bustedkiwi** [comment]
I did update the pastebin cause it was going haywire without the "muscle style" option in there even though most people seem to leave it blank.

From the console log:

Going from 0 to 10 for body_tattoo_metallic
body_tattoo_metallic, 10
Going from 50 to 25 for body_tattoo_sheen
body_tattoo_sheen, 25
Skipping move-down as edit = true
Going through markings_body_tattoos_2, for {'body_tattoo_style': 1, 'body_tattoo_primary_color': 1, 'body_tattoo_secondary_color': 1, 'body_tattoo_tertiary_color': 1, 'body_tattoo_vertical_pos': -45, 'body_tattoo_horizontal_pos': 0, 'body_tattoo_rotation': 0, 'body_tattoo_overall_scale': 25, 'body_tattoo_vert_scale': 25, 'body_tattoo_horz_scale': 25, 'body_tattoo_vert_tiling': 1, 'body_tattoo_horz_tiling': 1, 'body_tattoo_opacity': 100, 'body_tattoo_nose_intensity': 0, 'body_tattoo_metallic': 0, 'body_tattoo_sheen': 50} on page: markings
Found section markings_body_tattoos_2 in target_attributes, entering
We are at location category
Going from 1 to 36 for body_tattoo_style
body_tattoo_style, 36
Going from 1 to 1 for body_tattoo_primary_color
body_tattoo_primary_color, 1
Going from 1 to 1 for body_tattoo_secondary_color
body_tattoo_secondary_color, 1
Going from 1 to 1 for body_tattoo_tertiary_color

**Comment by Mx772** [comment]
Yeah, I found the issue, fixing now :)

**Comment by Mx772** [comment]
fixed in #22

**Comment by bustedkiwi** [comment]
Nice! Scars and tatts working perfect!

The only other issue I've noticed is something goes a little off on eye squint - Ciri here for example should end up with 90/90 squint but somehow ends up with 60/0. Everything else is solid

**Comment by Mx772** [comment]
Very strange, will look into it later tonight!

Thanks for the update!

**Comment by Mx772** [comment]
Fixed in latest release 👍
