### ISSUE TITLE
Body Menu 

### ISSUE THREAD

**Issue by Hinata500** [Mx772/dragons-dogma-2-auto-character-creator#27]
Im using a Template for Slider but i t stays on the Menu when i use it. its the Idu and Brakka mods it just does not want to move to adjusting the other body parts when i use the template in slider i cant post the templates in here i guess first time here

**Comment by Mx772** [comment]
What version?

Also can you upload the target config.ini?

Additionally, the console should output some logs, if you could provide those.

My educated guess from looking at the mod https://www.nexusmods.com/dragonsdogma2/mods/158 is that it uses the old config.ini style.

I would update it, but I think the user expressed wanting to have the file on nexus and not included by default in the tool.

**Comment by Mx772** [comment]
Can confirm this is the issue:

```
[Character]
; FEMALE PRESET - ONLY WORKS FOR FEMALES
; Body
height = 215
torso = 53
muscle_style = 8
muscle_strength = 100
traps = 51
upper_mass = 89
lower_mass = 90
upper_size = 0
lower_size = 33

; Head
head_size = -36
head_length = 10
head_width = -2
head_depth = -42
face_height = 82
neck_length = 52
neck_thickness = 31 
```

Is the old format. Needs to be updated.

**Comment by Mx772** [comment]
I've pinged the mod author:
https://github.com/Mx772/dragons-dogma-2-auto-character-creator/issues/9

**Comment by Mx772** [comment]
They note it's fixed in their latest patch.
