### ISSUE TITLE
exe starts and closes immediately

### ISSUE THREAD

**Issue by Merlinix** [Mx772/dragons-dogma-2-auto-character-creator#34]
**Describe the bug**
Running the .exe normally or as administrator causes a cmd to flash (open and close very quickly). No GUI appears.

**Version:**
v0.0.13

**Python Version**
3.12.2

**To Reproduce**
1. Go to 'C:\Users\*\Desktop\DD2AutoSlider'
2. Click on 'DD2AutoSlider.exe'

**Preset/Template**
Can't get that far

**Expected behavior**
A GUI appears

**Screenshots**
No added context

**Desktop (please complete the following information):**
Edition	Windows 11 Home
Version	23H2
Installed on	‎3/‎22/‎2024
OS build	22631.3296
Experience	Windows Feature Experience Pack 1000.22687.1000.0

**Comment by Mx772** [comment]
Could you open a terminal in that folder and type in DD2 then push tab, it should auto select the exe file. Then push enter to run it.

It should give an error, can you let me know what that error is?

I'm assuming it's about a missing dll or something but I can't reproduce on my end.

**Comment by dryada95787** [comment]
I have a same issue. 
Here is the error:
Traceback (most recent call last):
  File "C:\Users\mxrid\OneDrive\Projects\DDCC\venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
  File "C:\Users\mxrid\OneDrive\Projects\DDCC\venv\Lib\site-packages\cx_Freeze\initscripts\console.py", line 17, in run
  File "src\main.py", line 3, in <module>
ImportError: DLL load failed while importing win32gui: The specified module could not be found.

**Comment by Mx772** [comment]
Give me a minute, I'm gonna kick off a GitHub build and see if that works for you.

**Comment by Mx772** [comment]
Try this one:
https://github.com/Mx772/dragons-dogma-2-auto-character-creator/actions/runs/8498655211/artifacts/1372716198

**Comment by Mx772** [comment]
[DD2AutoSlider.zip](https://github.com/Mx772/dragons-dogma-2-auto-character-creator/files/14816102/DD2AutoSlider.zip)
Try this one

**Comment by dryada95787** [comment]
it work for me.
Thank you.

**Comment by Nypheena** [comment]
I get the same issue with 13 where 12 worked for me and same error, the one you provided here works for me

**Comment by Mx772** [comment]
Updated Nexus and release for 13. I used a different build tool which doesn't seem to work for everyone.
