### ISSUE TITLE
Exception in Tkinter callback with belaDimitrescu.ini

### ISSUE THREAD

**Issue by Kitthaven** [Mx772/dragons-dogma-2-auto-character-creator#35]
**Describe the bug**
I'm going to contribute some full body pictures of the templates that are missing photos and trying to use the belaDimitrescu template causes this error in the console:

`
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mxrid\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
  File "src\main.py", line 289, in run_program
  File "src\main.py", line 307, in main
  File "src\main.py", line 37, in read_config
  File "src\main.py", line 38, in <dictcomp>
ValueError: invalid literal for int() with base 10: 'skip'
`
So far I have only done arwen as I'm going in alphabetical order and arwen ran just fine so I'm not sure if it's an issue with this .ini or not.

**Version:**
v0.0.13

**To Reproduce**
Try to run the belaDimitrescu.ini through the Auto Slider.

**Preset/Template**
I'm using the default one included in the script, unaltered.

**Screenshots**
![2024-03-31 16_14_38-New Issue · Mx772_dragons-dogma-2-auto-character-creator - Opera](https://github.com/Mx772/dragons-dogma-2-auto-character-creator/assets/50052152/2745bd35-1866-43a2-9870-4f9a95da1fdd)
I tried running it twice. I also tried rebooting the program as well as restarting the DD2 character creator just in case and it always gave this error.

**Desktop (please complete the following information):**
Windows 11

Thanks!

**Comment by Mx772** [comment]
Should be fixed with https://github.com/Mx772/dragons-dogma-2-auto-character-creator/commit/d63aa2244847821236b8e1bb9c915246a17a25a2
