### ISSUE TITLE
Human male doesn't seem to work

### ISSUE THREAD

**Issue by unleashed7** [Mx772/dragons-dogma-2-auto-character-creator#38]
While the Human Female works, I can't seem to make the Male script work.

For example below I only changed 5 values compared to the default ini, and it seems to break it.

Values changed for testing:
```
[head_base_head]
base_head = 1
base_skin = 1
skin_color = 1
wrinkles = 1
skin_sheen = 1
```

Result:

https://github.com/Mx772/dragons-dogma-2-auto-character-creator/assets/49449100/83e486ba-c383-4740-94f8-21e6e1a8d59b

**Comment by Mx772** [comment]
Good find, for some reason I never noticed [head_skin] wasn't on the default male.

**Comment by Mx772** [comment]
Fixed via https://github.com/Mx772/dragons-dogma-2-auto-character-creator/commit/4dce970a7783e6356fdb991b1dac37446f5a2e92
