### ISSUE TITLE
Just some comments/ideas

### ISSUE THREAD

**Issue by hami1810** [Mx772/dragons-dogma-2-auto-character-creator#4]
Hi there,

Just some ideas when I looked through the code:
- Did you try using pynput or the default keyboard, mouse libraries for button press/release? I think it might would be easier to implement
- I also thought about using the mouse drag and release to move the sliders, instead of pressing keyboard buttons repeatedly, together with screengrab to find the slider positions and evaluate the actual values. But I think it would make everything overly complex and would cause more issues to solve to get the precision right.

**Comment by Mx772** [comment]
> I also thought about using the mouse drag and release to move the sliders, instead of pressing keyboard buttons repeatedly, together with screengrab to find the slider positions and evaluate the actual values. But I think it would make everything overly complex and would cause more issues to solve to get the precision right.

I had tried this, and it ends up causing issues with different resolutions, languages, and mouse sensitivity. I basically ruled it out. 

> Did you try using pynput or the default keyboard, mouse libraries for button press/release? I think it might would be easier to implement

I tried quite a few packages, such as pyautogui, etc. Most didn't work (which is how I ended up on that stackoverflow answer.)
Additionally, a few options did seem to 'work', but they had 100+ dependencies which was wild when I could have it working via native modules. But I'm open to trying some others.
