### ISSUE TITLE
Small bug and question

### ISSUE THREAD

**Issue by ItsJawn** [Mx772/dragons-dogma-2-auto-character-creator#9]
Just wanted to let you know the female default you provided has the arm tattoo vertical positions at -45 then they should be at 0, no big deal. 

Also, how does this exactly work when it comes to the additional edit options? Could I just simply copy the list under the first and add a 2 after body/left/right?

**Comment by Mx772** [comment]
Thanks! I'll get that fixed ASAP!

Unfortunately I haven't configured the edit options yet where it toggles more settings, I need to go through a figure out a good way. I have a few ideas though so don't.

**Comment by ItsJawn** [comment]
Sound good! I'll share my presets to Nexus to help get attention to this now that it works perfectly! 

Also, not sure if you can do this but I noticed when I had a missing int it gave an error which is fine, but could you configure it to default the missing int to 0 but still show in console "Missing Int X, defaulting to default.ini"

**Comment by Mx772** [comment]
Good idea, can implement!

If you want you can also submit any presents as a Pull request here to get it included by default!

**Comment by ItsJawn** [comment]
They are uploaded!
https://www.nexusmods.com/dragonsdogma2/mods/158

Thinking about it, I think it would defeat the purpose of pick and choosing presets if they are all included as defaults. Thank you for the offer though! If I think of other options or recommendations I'll let you know!

**Comment by Mx772** [comment]
Oh yeah, it would just be included in the templates if you wanted. 

Just as a 'easy-pick' if people wanted. 

Wanted to give some options to people to see how it works before they dived in kinda deal. 

I'm hoping to work with Nexus to find a way to get it auto-approved since right now they are manually approving it...

I'm not entirely sure why their system is flagging it besides possibly because it includes a nested zip... But several other mods are using the same packaging which includes the same zip; and they've yet responded so. /shrug

**Comment by ItsJawn** [comment]
Hmmm, how hard would it be to implement something like a "Community presets button"? Something that would pull up a separate window with preset pictures, an install button, and of course providing a link to the nexus page if provided. 

This would allow users to just unpack provided presets (without being flooded with options on default menu) that are included WITH the auto slider, give a link to the original presets for any updates to them, and provide a way to give examples of how to make presets. Like, once you figure out the toggle edit 2 options I'm using it lol 

Also, would it be possible to have the browse button replaced with a drop down menu that allocates its names form the templates folder? You can of course just move the browse option as a back up, but just a thought to I guess.

**Comment by Mx772** [comment]
Heads up; I rewrote the entire config logic, take a look. 
Sorry about that, but some of the issues/bugs couldn't be fixed with 'math' based logic.

**Comment by Mx772** [comment]
@ItsJawn Heads up, users are making issues for your mod:
https://github.com/Mx772/dragons-dogma-2-auto-character-creator/issues/27#issue-2214683583

Looks like it needs be updated to the latest formatting. (See the new defaults)
(You can use the new tool OR just convert the headers)
